title: Train MF

device: &device cuda:0
parallel: false

task:
  object: modelling

data:
  train:
    name: book
    mode: train
    train_size: 0.75
    data_path: data/BookRecommendation/Ratings.csv

model:
  name: MF
  num_users: 105283 # dataset script로 확인
  num_items: 340556 # dataset script로 확인
  latent_dim: 200
  use_bias: false

hyperparameters:
  optim: Adam
  lr: 0.0002
  batch_size: 512
  epochs: 100
  weight_decay: 0.00005

save:
  name: mf.book
  weights_path: saved/weights
  loss_path: saved/loss